### ISSUE TITLE
SDK version for M1065-L

### ISSUE THREAD

**Issue by qolson5** [AxisCommunications/discussions#247]
I am attempting to install the hello_world app on an M1065-L, I can do a container build, create the .eap file, but the install fails with the message:

> eap-install.sh install

2023-05-17T09:54:15.373-08:00 axis-b8a44f5cfea5 [ CRIT    ] acap-install: Invalid embedded development version "2.16". "hello_world" require at least version 3.0.

How can I tell if this device is supported?

"ProdNbr": "M1065-L",
"Version": "9.80.28",

**Comment by mattias-kindborg-at-work** [comment]
Sorry for late reply. I'd recommend that you ask the question in the specific repository. You will have a much greater chance of getting an answer there.
