### ISSUE TITLE
fflprapp allow_list.cgi and api.cgi problems

### ISSUE THREAD

**Issue by lacmuch** [AxisCommunications/discussions#590]
### Discussed in https://github.com/orgs/AxisCommunications/discussions/589

<div type='discussions-op-text'>

<sup>Originally posted by **lacmuch** April 10, 2024</sup>
Dear Community!

If the XML body of the request sent to the http://<servername>/local/fflprapp/allow_list.cgi endpoint is larger than about 36361 bytes, it will not be processed and the fflprapp process will freeze and become unavailable, it must be restarted. We tested it on several types of cameras and firmware versions, and the results are the same everywhere. We did not find any relevant information in the logs. Of course, a request from Postman also produces this.

Another problem: http://<servername>/local/fflprapp/api.cgi?api=delplate&plate=<plate>&list=allow license plate deletion simply does not work, it does not remove the license plate from the whitelist, even with a status of 200 OK the request is returned.

Can someone help?</div>

**Comment by mattias-kindborg-at-work** [comment]
This issue does not related to this repository. You've successfully created a discussion and seem to get some answers there, I'm closing this one.
